# Generated by Django 5.1.3 on 2024-11-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id_char', models.AutoField(primary_key=True, serialize=False)),
                ('char_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEquipment',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id_workers', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory1C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounting_name', models.TextField()),
                ('real_name', models.TextField()),
                ('inventory_decimal', models.TextField()),
                ('date_acceptance_accounting', models.DateField()),
                ('date_of_decommission', models.DateField(blank=True, null=True)),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.typeofequipment')),
                ('id_workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Relation4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('characteristics_id_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.characteristics')),
                ('inventory_1c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.inventory1c')),
            ],
            options={
                'unique_together': {('inventory_1c_id', 'characteristics_id_char')},
            },
        ),
        migrations.CreateModel(
            name='Relation3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics_id_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.characteristics')),
                ('type_of_equipment_id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invAPP.typeofequipment')),
            ],
            options={
                'unique_together': {('type_of_equipment_id_type', 'characteristics_id_char')},
            },
        ),
    ]
