# Generated by Django 4.2.16 on 2024-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invAPP', '0002_remove_inventory1c_date_of_decommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory1c',
            name='date_of_decommission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
