# Generated by Django 4.2.16 on 2024-12-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invAPP', '0003_inventory1c_date_of_decommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory1c',
            name='date_of_decommission',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory1c',
            name='initial_cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
